/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedDepartmentsIndexRouteImport } from './routes/_authenticated/departments/index'
import { Route as AuthenticatedDepartmentsDepartmentIdRouteImport } from './routes/_authenticated/departments/$departmentId'
import { Route as AuthenticatedEmployeesIndexRouteImport } from './routes/_authenticated/employees/index'
import { Route as AuthenticatedEmployeesEmployeeIdRouteImport } from './routes/_authenticated/employees/$employeeId'
import { Route as AuthenticatedEmployeesNewRouteImport } from './routes/_authenticated/employees/new'
import { Route as AuthenticatedEmployeesEmployeeIdIndexRouteImport } from './routes/_authenticated/employees/$employeeId/index'
import { Route as AuthenticatedEmployeesEmployeeIdEditRouteImport } from './routes/_authenticated/employees/$employeeId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDepartmentsIndexRoute =
  AuthenticatedDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDepartmentsDepartmentIdRoute =
  AuthenticatedDepartmentsDepartmentIdRouteImport.update({
    id: '/departments/$departmentId',
    path: '/departments/$departmentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesIndexRoute =
  AuthenticatedEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesEmployeeIdRoute =
  AuthenticatedEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesNewRoute =
  AuthenticatedEmployeesNewRouteImport.update({
    id: '/employees/new',
    path: '/employees/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesEmployeeIdIndexRoute =
  AuthenticatedEmployeesEmployeeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmployeesEmployeeIdRoute,
  } as any)
const AuthenticatedEmployeesEmployeeIdEditRoute =
  AuthenticatedEmployeesEmployeeIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedEmployeesEmployeeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/departments/$departmentId': typeof AuthenticatedDepartmentsDepartmentIdRoute
  '/employees/$employeeId': typeof AuthenticatedEmployeesEmployeeIdRouteWithChildren
  '/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/departments/': typeof AuthenticatedDepartmentsIndexRoute
  '/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/employees/$employeeId/edit': typeof AuthenticatedEmployeesEmployeeIdEditRoute
  '/employees/$employeeId/': typeof AuthenticatedEmployeesEmployeeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/departments/$departmentId': typeof AuthenticatedDepartmentsDepartmentIdRoute
  '/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/departments': typeof AuthenticatedDepartmentsIndexRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/employees/$employeeId/edit': typeof AuthenticatedEmployeesEmployeeIdEditRoute
  '/employees/$employeeId': typeof AuthenticatedEmployeesEmployeeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/departments/$departmentId': typeof AuthenticatedDepartmentsDepartmentIdRoute
  '/_authenticated/employees/$employeeId': typeof AuthenticatedEmployeesEmployeeIdRouteWithChildren
  '/_authenticated/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/_authenticated/departments/': typeof AuthenticatedDepartmentsIndexRoute
  '/_authenticated/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/_authenticated/employees/$employeeId/edit': typeof AuthenticatedEmployeesEmployeeIdEditRoute
  '/_authenticated/employees/$employeeId/': typeof AuthenticatedEmployeesEmployeeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/departments/$departmentId'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/departments/'
    | '/employees/'
    | '/employees/$employeeId/edit'
    | '/employees/$employeeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/departments/$departmentId'
    | '/employees/new'
    | '/departments'
    | '/employees'
    | '/employees/$employeeId/edit'
    | '/employees/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/departments/$departmentId'
    | '/_authenticated/employees/$employeeId'
    | '/_authenticated/employees/new'
    | '/_authenticated/departments/'
    | '/_authenticated/employees/'
    | '/_authenticated/employees/$employeeId/edit'
    | '/_authenticated/employees/$employeeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/departments/': {
      id: '/_authenticated/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof AuthenticatedDepartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/departments/$departmentId': {
      id: '/_authenticated/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof AuthenticatedDepartmentsDepartmentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/': {
      id: '/_authenticated/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthenticatedEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/$employeeId': {
      id: '/_authenticated/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AuthenticatedEmployeesEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/new': {
      id: '/_authenticated/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AuthenticatedEmployeesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/$employeeId/': {
      id: '/_authenticated/employees/$employeeId/'
      path: '/'
      fullPath: '/employees/$employeeId/'
      preLoaderRoute: typeof AuthenticatedEmployeesEmployeeIdIndexRouteImport
      parentRoute: typeof AuthenticatedEmployeesEmployeeIdRoute
    }
    '/_authenticated/employees/$employeeId/edit': {
      id: '/_authenticated/employees/$employeeId/edit'
      path: '/edit'
      fullPath: '/employees/$employeeId/edit'
      preLoaderRoute: typeof AuthenticatedEmployeesEmployeeIdEditRouteImport
      parentRoute: typeof AuthenticatedEmployeesEmployeeIdRoute
    }
  }
}

interface AuthenticatedEmployeesEmployeeIdRouteChildren {
  AuthenticatedEmployeesEmployeeIdEditRoute: typeof AuthenticatedEmployeesEmployeeIdEditRoute
  AuthenticatedEmployeesEmployeeIdIndexRoute: typeof AuthenticatedEmployeesEmployeeIdIndexRoute
}

const AuthenticatedEmployeesEmployeeIdRouteChildren: AuthenticatedEmployeesEmployeeIdRouteChildren =
  {
    AuthenticatedEmployeesEmployeeIdEditRoute:
      AuthenticatedEmployeesEmployeeIdEditRoute,
    AuthenticatedEmployeesEmployeeIdIndexRoute:
      AuthenticatedEmployeesEmployeeIdIndexRoute,
  }

const AuthenticatedEmployeesEmployeeIdRouteWithChildren =
  AuthenticatedEmployeesEmployeeIdRoute._addFileChildren(
    AuthenticatedEmployeesEmployeeIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDepartmentsDepartmentIdRoute: typeof AuthenticatedDepartmentsDepartmentIdRoute
  AuthenticatedEmployeesEmployeeIdRoute: typeof AuthenticatedEmployeesEmployeeIdRouteWithChildren
  AuthenticatedEmployeesNewRoute: typeof AuthenticatedEmployeesNewRoute
  AuthenticatedDepartmentsIndexRoute: typeof AuthenticatedDepartmentsIndexRoute
  AuthenticatedEmployeesIndexRoute: typeof AuthenticatedEmployeesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDepartmentsDepartmentIdRoute:
    AuthenticatedDepartmentsDepartmentIdRoute,
  AuthenticatedEmployeesEmployeeIdRoute:
    AuthenticatedEmployeesEmployeeIdRouteWithChildren,
  AuthenticatedEmployeesNewRoute: AuthenticatedEmployeesNewRoute,
  AuthenticatedDepartmentsIndexRoute: AuthenticatedDepartmentsIndexRoute,
  AuthenticatedEmployeesIndexRoute: AuthenticatedEmployeesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
